//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTestAngularJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTab
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ExpiriyDate { get; set; }
        public string Languages { get; set; }
        public string Tag { get; set; }
        public string Payment { get; set; }
    }
}
